# Generated by Django 4.2.7 on 2025-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(to='core.service'),
        ),
    ]
