# Generated by Django 4.2.7 on 2025-04-23 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprofessional'),
        ),
    ]
