# Generated by Django 4.2.7 on 2025-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reservation_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_and_date',
            field=models.DateTimeField(),
        ),
    ]
